### ISSUE TITLE
Lightware 3 / Feedback

### ISSUE THREAD

**Issue by sjtinsley83** [bitfocus/companion-module-lightware-lw3#4]
I would like to implement feedback with this module, but unsure how to achieve this.
I have forked the module and made some changes, but need some assistance to complete:
[https://github.com/sjtinsley83/companion-module-lightware3](url)

Can someone help?

**Comment by McHauge** [comment]
@sjtinsley83 Guess you already have the documentation on the lightware 3, and have an idea about what options there are in it, that could be used as feedback.

What I did to get an idea on how to do feedbacks (still new to feedbacks myself) was to look at other modules and try and poke around to see how it was done there. Together with the small amount about it on the wiki (under module dev). Especially the 'bmd-teranex' module offered quid a bit of help on my way, since it's a small module, therefore, simpler to analyze. And helped me making my rewrite on the 'christiepj' module, which now has feedbacks based on the same execution

Hope it helps a bit.

**Comment by sjtinsley83** [comment]
Looking at the manual it looks like I need to get hold of the unit to get all the responses.
I think its halfway there tho.

**Comment by dnmeid** [comment]
Feedbacks are now available in latest Beta.
